Homework 2
================
Mayuri Albal
2022-09-30

``` r
library(tidyverse)
```

    ## ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──
    ## ✔ ggplot2 3.3.6      ✔ purrr   0.3.4 
    ## ✔ tibble  3.1.8      ✔ dplyr   1.0.10
    ## ✔ tidyr   1.2.0      ✔ stringr 1.4.1 
    ## ✔ readr   2.1.2      ✔ forcats 0.5.2 
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()

``` r
library(dplyr)
library(readxl)
```

\#Problem 1

\###Cleaning

``` r
nyc_transit=read_csv('/Users/mayurialbal/Documents/Data Science/Homework/HW2/HW2/NYC_Transit_Subway_Entrance_And_Exit_Data.csv',
      col_types=cols(Route8 ='c', Route9 ='c', Route10 ='c', Route11 ='c')) %>%
  janitor::clean_names() %>%
select(line, station_name, station_latitude, station_longitude, entry, exit_only, vending,
         entrance_type, ada, starts_with("route")) %>%
  mutate(entry= ifelse(entry== 'YES', TRUE, FALSE))
```

\####Explanation Currently the data set contains the variables: line,
station name, station latitude, station longitude, routes served (1-11),
entry, vending, entrance type, as well as if the station is ADA
compliant. In order to get to this data set, it was essential to clean
the variable names from the way they were converted in order to be
interpretable for R. After this, the variables that were intended to be
analysed were ‘selected’ from the data set to be used. Lastly, the
variable entry was altered in order have it read as a logic variable
rather than a character variable, thus yes was interpreted as True, and
no as False. The data is not currently ‘tidy’ at this point as route is
still appearing as NA due to its format and thus unusable until it is
altered. There are currently 20 columns and 1,868 rows in the current
dataset.

\####Distinct Stations

``` r
nyc_transit%>%
  select(station_name,line) %>%
distinct
```

    ## # A tibble: 465 × 2
    ##    station_name             line    
    ##    <chr>                    <chr>   
    ##  1 25th St                  4 Avenue
    ##  2 36th St                  4 Avenue
    ##  3 45th St                  4 Avenue
    ##  4 53rd St                  4 Avenue
    ##  5 59th St                  4 Avenue
    ##  6 77th St                  4 Avenue
    ##  7 86th St                  4 Avenue
    ##  8 95th St                  4 Avenue
    ##  9 9th St                   4 Avenue
    ## 10 Atlantic Av-Barclays Ctr 4 Avenue
    ## # … with 455 more rows

There are 465 distinct stations.

\####ADA Compliance

``` r
nyc_transit %>% 
  filter(ada == TRUE) %>% 
  select(station_name, line) %>% 
  distinct
```

    ## # A tibble: 84 × 2
    ##    station_name                   line           
    ##    <chr>                          <chr>          
    ##  1 Atlantic Av-Barclays Ctr       4 Avenue       
    ##  2 DeKalb Av                      4 Avenue       
    ##  3 Pacific St                     4 Avenue       
    ##  4 Grand Central                  42nd St Shuttle
    ##  5 34th St                        6 Avenue       
    ##  6 47-50th Sts Rockefeller Center 6 Avenue       
    ##  7 Church Av                      6 Avenue       
    ##  8 21st St                        63rd Street    
    ##  9 Lexington Av                   63rd Street    
    ## 10 Roosevelt Island               63rd Street    
    ## # … with 74 more rows

Of the 465 distinct stations, 84 are ADA compliant.

\####Proportion of Allowed Entrances

``` r
nyc_transit %>% 
  filter(vending == "NO") %>% 
  pull(entry) %>% 
  mean
```

    ## [1] 0.3770492

The proportion of entrances/exits without vending allowed entrance is
0.377.

\####Serve ‘A’ Train

``` r
nyc_transit %>% 
  pivot_longer(
    route1:route11,
    names_to = "route_num",
    values_to = "route") %>% 
  filter(route == "A") %>% 
  select(station_name, line) %>% 
  distinct
```

    ## # A tibble: 60 × 2
    ##    station_name                  line           
    ##    <chr>                         <chr>          
    ##  1 Times Square                  42nd St Shuttle
    ##  2 125th St                      8 Avenue       
    ##  3 145th St                      8 Avenue       
    ##  4 14th St                       8 Avenue       
    ##  5 168th St - Washington Heights 8 Avenue       
    ##  6 175th St                      8 Avenue       
    ##  7 181st St                      8 Avenue       
    ##  8 190th St                      8 Avenue       
    ##  9 34th St                       8 Avenue       
    ## 10 42nd St                       8 Avenue       
    ## # … with 50 more rows

60 distinct stations serve the A train.

\####Serve ‘A’ Train and ADA compliant

``` r
nyc_transit %>% 
  pivot_longer(
    route1:route11,
    names_to = "route_num",
    values_to = "route") %>% 
  filter(route == "A", ada == TRUE) %>% 
  select(station_name, line) %>% 
  distinct
```

    ## # A tibble: 17 × 2
    ##    station_name                  line            
    ##    <chr>                         <chr>           
    ##  1 14th St                       8 Avenue        
    ##  2 168th St - Washington Heights 8 Avenue        
    ##  3 175th St                      8 Avenue        
    ##  4 34th St                       8 Avenue        
    ##  5 42nd St                       8 Avenue        
    ##  6 59th St                       8 Avenue        
    ##  7 Inwood - 207th St             8 Avenue        
    ##  8 West 4th St                   8 Avenue        
    ##  9 World Trade Center            8 Avenue        
    ## 10 Times Square-42nd St          Broadway        
    ## 11 59th St-Columbus Circle       Broadway-7th Ave
    ## 12 Times Square                  Broadway-7th Ave
    ## 13 8th Av                        Canarsie        
    ## 14 Franklin Av                   Franklin        
    ## 15 Euclid Av                     Fulton          
    ## 16 Franklin Av                   Fulton          
    ## 17 Howard Beach                  Rockaway

Of the 60 distinct stations that serve the A train, 17 are ADA
compliant.

\##Problem 2

\###Mr. Trash Wheel Data Set Cleaning

``` r
mr_trash_wheel = 
  read_excel("Trash Wheel Collection Data.xlsx", 
    sheet = "Mr. Trash Wheel", col_names= TRUE) %>%
janitor::clean_names() %>%
  select(-x15, -x16) %>%
  drop_na(dumpster) %>%
  mutate(
    year = as.numeric(year),
  sports_balls= round(sports_balls),
  trash_wheel_data= "mrt" ) %>%
  select(trash_wheel_data, everything()) 
```

    ## New names:
    ## • `` -> `...15`
    ## • `` -> `...16`

``` r
view(mr_trash_wheel)
skimr::skim(mr_trash_wheel)
```

|                                                  |                |
|:-------------------------------------------------|:---------------|
| Name                                             | mr_trash_wheel |
| Number of rows                                   | 547            |
| Number of columns                                | 15             |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_   |                |
| Column type frequency:                           |                |
| character                                        | 2              |
| numeric                                          | 12             |
| POSIXct                                          | 1              |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ |                |
| Group variables                                  | None           |

Data summary

**Variable type: character**

| skim_variable    | n_missing | complete_rate | min | max | empty | n_unique | whitespace |
|:-----------------|----------:|--------------:|----:|----:|------:|---------:|-----------:|
| trash_wheel_data |         0 |             1 |   3 |   3 |     0 |        1 |          0 |
| month            |         0 |             1 |   3 |   9 |     0 |       13 |          0 |

**Variable type: numeric**

| skim_variable      | n_missing | complete_rate |     mean |       sd |      p0 |     p25 |     p50 |      p75 |      p100 | hist  |
|:-------------------|----------:|--------------:|---------:|---------:|--------:|--------:|--------:|---------:|----------:|:------|
| dumpster           |         0 |          1.00 |   274.00 |   158.05 |    1.00 |  137.50 |  274.00 |   410.50 |    547.00 | ▇▇▇▇▇ |
| year               |         0 |          1.00 |  2017.97 |     2.37 | 2014.00 | 2016.00 | 2018.00 |  2020.00 |   2022.00 | ▇▆▆▇▆ |
| weight_tons        |         0 |          1.00 |     3.20 |     0.75 |    0.78 |    2.71 |    3.19 |     3.72 |      5.62 | ▁▃▇▅▁ |
| volume_cubic_yards |         0 |          1.00 |    15.33 |     1.38 |    7.00 |   15.00 |   15.00 |    15.00 |     20.00 | ▁▁▁▇▂ |
| plastic_bottles    |         0 |          1.00 |  1958.49 |  1063.82 |  210.00 |  980.00 | 1880.00 |  2740.00 |   5960.00 | ▇▇▅▁▁ |
| polystyrene        |         0 |          1.00 |  1649.08 |  1218.77 |   48.00 |  695.00 | 1250.00 |  2480.00 |   6540.00 | ▇▅▃▁▁ |
| cigarette_butts    |         0 |          1.00 | 20925.08 | 30215.86 |  900.00 | 4000.00 | 7000.00 | 26500.00 | 310000.00 | ▇▁▁▁▁ |
| glass_bottles      |         0 |          1.00 |    21.65 |    16.40 |    0.00 |   10.00 |   18.00 |    31.00 |    110.00 | ▇▃▁▁▁ |
| grocery_bags       |         0 |          1.00 |   965.53 |   844.77 |   24.00 |  330.00 |  680.00 |  1370.00 |   3750.00 | ▇▃▂▁▁ |
| chip_bags          |         0 |          1.00 |  1418.59 |   921.99 |  180.00 |  740.00 | 1100.00 |  1980.00 |   5085.00 | ▇▃▂▁▁ |
| sports_balls       |         0 |          1.00 |    12.57 |     9.27 |    0.00 |    6.00 |   11.00 |    18.00 |     56.00 | ▇▅▂▁▁ |
| homes_powered      |        61 |          0.89 |    45.98 |    21.42 |    0.00 |   39.54 |   51.17 |    59.13 |     93.67 | ▂▂▇▆▁ |

**Variable type: POSIXct**

| skim_variable | n_missing | complete_rate | min        | max        | median     | n_unique |
|:--------------|----------:|--------------:|:-----------|:-----------|:-----------|---------:|
| date          |         0 |             1 | 1900-01-20 | 2022-07-29 | 2018-07-18 |      331 |

\###Professor Trash Wheel Data Set Cleaning

``` r
prof_trash_wheel = 
  read_excel("Trash Wheel Collection Data.xlsx", 
    sheet = "Professor Trash Wheel", range= "A2:M96") %>%
janitor::clean_names() %>%
  drop_na(dumpster) %>%
  mutate(
    as.numeric(year),
  trash_wheel_data= "proft") %>%
  select(trash_wheel_data, everything()) 
view(prof_trash_wheel)
skimr::skim(prof_trash_wheel)
```

|                                                  |                  |
|:-------------------------------------------------|:-----------------|
| Name                                             | prof_trash_wheel |
| Number of rows                                   | 94               |
| Number of columns                                | 15               |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_   |                  |
| Column type frequency:                           |                  |
| character                                        | 2                |
| numeric                                          | 12               |
| POSIXct                                          | 1                |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ |                  |
| Group variables                                  | None             |

Data summary

**Variable type: character**

| skim_variable    | n_missing | complete_rate | min | max | empty | n_unique | whitespace |
|:-----------------|----------:|--------------:|----:|----:|------:|---------:|-----------:|
| trash_wheel_data |         0 |             1 |   5 |   5 |     0 |        1 |          0 |
| month            |         0 |             1 |   3 |   9 |     0 |       12 |          0 |

**Variable type: numeric**

| skim_variable      | n_missing | complete_rate |     mean |      sd |      p0 |     p25 |     p50 |      p75 |     p100 | hist  |
|:-------------------|----------:|--------------:|---------:|--------:|--------:|--------:|--------:|---------:|---------:|:------|
| dumpster           |         0 |          1.00 |    47.50 |   27.28 |    1.00 |   24.25 |   47.50 |    70.75 |    94.00 | ▇▇▇▇▇ |
| year               |         0 |          1.00 |  2019.11 |    1.64 | 2017.00 | 2018.00 | 2019.00 |  2020.75 |  2022.00 | ▇▃▂▃▂ |
| weight_tons        |         0 |          1.00 |     2.02 |    0.67 |    0.61 |    1.58 |    1.94 |     2.49 |     3.72 | ▃▇▆▅▂ |
| volume_cubic_yards |         0 |          1.00 |    14.59 |    1.64 |    6.00 |   15.00 |   15.00 |    15.00 |    18.00 | ▁▁▁▇▁ |
| plastic_bottles    |         0 |          1.00 |  5411.13 | 2411.88 |  657.00 | 3925.00 | 5050.00 |  7400.00 |  9830.00 | ▃▅▇▅▅ |
| polystyrene        |         0 |          1.00 |  4647.71 | 3283.68 |  280.00 | 1534.75 | 4000.00 |  7800.00 | 11528.00 | ▇▇▂▆▂ |
| cigarette_butts    |         0 |          1.00 | 12324.23 | 6602.04 | 4200.00 | 7250.00 | 9700.00 | 16000.00 | 33320.00 | ▇▃▂▁▁ |
| glass_bottles      |         0 |          1.00 |    15.20 |   10.33 |    0.00 |    6.50 |   14.00 |    22.00 |    48.00 | ▇▇▆▂▁ |
| grocery_bags       |         0 |          1.00 |  2684.83 | 3412.14 |  270.00 |  882.50 | 1200.00 |  2050.00 | 13450.00 | ▇▁▁▁▁ |
| chip_bags          |         0 |          1.00 |  8148.74 | 4467.53 | 2900.00 | 4900.00 | 6400.00 | 10400.00 | 20100.00 | ▇▃▂▂▁ |
| homes_powered      |        12 |          0.87 |    33.04 |   10.80 |   10.17 |   26.33 |   31.08 |    40.88 |    62.00 | ▃▇▆▅▂ |
| as.numeric(year)   |         0 |          1.00 |  2019.11 |    1.64 | 2017.00 | 2018.00 | 2019.00 |  2020.75 |  2022.00 | ▇▃▂▃▂ |

**Variable type: POSIXct**

| skim_variable | n_missing | complete_rate | min        | max        | median     | n_unique |
|:--------------|----------:|--------------:|:-----------|:-----------|:-----------|---------:|
| date          |         0 |             1 | 2017-01-02 | 2022-07-18 | 2019-04-24 |       92 |

\###Combining Mr. and Professor Trash Wheel Data Sets

``` r
trash_wd_tidy = bind_rows(mr_trash_wheel, prof_trash_wheel) %>% 
  janitor:: clean_names()
view(trash_wd_tidy)
skimr:: skim(trash_wd_tidy)
```

|                                                  |               |
|:-------------------------------------------------|:--------------|
| Name                                             | trash_wd_tidy |
| Number of rows                                   | 641           |
| Number of columns                                | 16            |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_   |               |
| Column type frequency:                           |               |
| character                                        | 2             |
| numeric                                          | 13            |
| POSIXct                                          | 1             |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ |               |
| Group variables                                  | None          |

Data summary

**Variable type: character**

| skim_variable    | n_missing | complete_rate | min | max | empty | n_unique | whitespace |
|:-----------------|----------:|--------------:|----:|----:|------:|---------:|-----------:|
| trash_wheel_data |         0 |             1 |   3 |   5 |     0 |        2 |          0 |
| month            |         0 |             1 |   3 |   9 |     0 |       13 |          0 |

**Variable type: numeric**

| skim_variable      | n_missing | complete_rate |     mean |       sd |      p0 |     p25 |     p50 |      p75 |      p100 | hist  |
|:-------------------|----------:|--------------:|---------:|---------:|--------:|--------:|--------:|---------:|----------:|:------|
| dumpster           |         0 |          1.00 |   240.78 |   166.88 |    1.00 |   81.00 |  227.00 |   387.00 |    547.00 | ▇▅▅▅▅ |
| year               |         0 |          1.00 |  2018.14 |     2.31 | 2014.00 | 2016.00 | 2018.00 |  2020.00 |   2022.00 | ▆▆▆▇▆ |
| weight_tons        |         0 |          1.00 |     3.02 |     0.84 |    0.61 |    2.48 |    3.08 |     3.62 |      5.62 | ▁▅▇▅▁ |
| volume_cubic_yards |         0 |          1.00 |    15.22 |     1.44 |    6.00 |   15.00 |   15.00 |    15.00 |     20.00 | ▁▁▁▇▁ |
| plastic_bottles    |         0 |          1.00 |  2464.81 |  1817.94 |  210.00 | 1110.00 | 2110.00 |  3100.00 |   9830.00 | ▇▆▁▁▁ |
| polystyrene        |         0 |          1.00 |  2088.81 |  1990.25 |   48.00 |  780.00 | 1460.00 |  2870.00 |  11528.00 | ▇▃▁▁▁ |
| cigarette_butts    |         0 |          1.00 | 19663.80 | 28187.00 |  900.00 | 4400.00 | 8000.00 | 23000.00 | 310000.00 | ▇▁▁▁▁ |
| glass_bottles      |         0 |          1.00 |    20.71 |    15.82 |    0.00 |    9.00 |   18.00 |    28.00 |    110.00 | ▇▃▁▁▁ |
| grocery_bags       |         0 |          1.00 |  1217.66 |  1634.36 |   24.00 |  360.00 |  780.00 |  1480.00 |  13450.00 | ▇▁▁▁▁ |
| chip_bags          |         0 |          1.00 |  2405.54 |  3050.01 |  180.00 |  800.00 | 1340.00 |  2684.00 |  20100.00 | ▇▁▁▁▁ |
| sports_balls       |        94 |          0.85 |    12.57 |     9.27 |    0.00 |    6.00 |   11.00 |    18.00 |     56.00 | ▇▅▂▁▁ |
| homes_powered      |        73 |          0.89 |    44.11 |    20.73 |    0.00 |   34.67 |   49.00 |    57.50 |     93.67 | ▂▃▇▅▁ |
| as_numeric_year    |       547 |          0.15 |  2019.11 |     1.64 | 2017.00 | 2018.00 | 2019.00 |  2020.75 |   2022.00 | ▇▃▂▃▂ |

**Variable type: POSIXct**

| skim_variable | n_missing | complete_rate | min        | max        | median     | n_unique |
|:--------------|----------:|--------------:|:-----------|:-----------|:-----------|---------:|
| date          |         0 |             1 | 1900-01-20 | 2022-07-29 | 2018-08-09 |      359 |

\####Explanation In this created data set, ‘trash_wd_tidy’, formed from
‘mr_trash_wheel’ and ‘prof_trash_wheel’, there are 641 observations and
16 variables. 547 of the variables were from the ‘mr_trash_wheel’ data
set while 94 were from the ‘prof_trash_wheel’ data. Some key variables
include: ‘weight_tons’, ‘volume_cubic_yards’, as well as ‘dumpster’. An
additional variable called ‘trash_wheel_data was used in order to
differentiate the two data sets when combining together. However, in
this updated data set, only ’mr_trash_wheel’ contained the variable for
sports_balls. This was not a variable in the updated
‘prof_trash_wheels’, thus it returned NA results in the ‘trash_wd_tidy’
data set created.

\####Total Weight of Trash Collected: Professor Trash Wheel

``` r
sum(prof_trash_wheel$weight_tons)
```

    ## [1] 190.12

The total weight of trash collected by Professor Trash Wheel was 190.12
tons.

\####Number of Sports Balls: Mr. Trash Wheel

``` r
sum(mr_trash_wheel$sports_balls)
```

    ## [1] 6877

``` r
sum(subset(mr_trash_wheel, year== '2020' )$sports_balls)
```

    ## [1] 856

The total number of balls collected by Mr. Trash Wheel in 2020 was 856
balls.

\##Problem 3

\###Pols-Month Data Cleaning

``` r
fte_pols = read_csv("/Users/mayurialbal/Documents/Data Science/Homework/HW2/HW2/fivethirtyeight_datasets/pols-month.csv") %>% 
  janitor::clean_names() %>% 
  separate(mon, c("year", "month", "day"), sep = "-") %>% 
  mutate( 
  month = recode(month,
      '01' = "january", '02'= "february", '03'= "march", '04'= "april", '05'= "may",
      '06'= "june", '07'= "july", '08'= "august", '09'= "september", '10'= "october", 
      '11' = "november", '12' = "december"),
  prez_dem= recode(prez_dem, "1"= "democrat" ),
  prez_gop= recode (prez_gop, "1"= "republican")) %>% 
  pivot_longer(cols= c("prez_dem", "prez_gop"),
               values_to= "president") %>% 
  drop_na ("president") %>% 
  select(-day,-name)
```

    ## Rows: 822 Columns: 9
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl  (8): prez_gop, gov_gop, sen_gop, rep_gop, prez_dem, gov_dem, sen_dem, r...
    ## date (1): mon
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

    ## Warning: Unreplaced values treated as NA as `.x` is not compatible.
    ## Unreplaced values treated as NA as `.x` is not compatible.
    ## Please specify replacements exhaustively or supply `.default`.

``` r
view(fte_pols)
```

\###SNP Data Cleaning

``` r
fte_snp = read_csv("/Users/mayurialbal/Documents/Data Science/Homework/HW2/HW2/fivethirtyeight_datasets/snp.csv") %>% 
  janitor::clean_names() %>% 
  mutate(
     date= as.Date(date,format= c("%m/%d/%y")),
     date= as.Date(ifelse(date > "2015-07-01", format(date,"19%y-%m-%d"), format(date)))) %>%
  separate(date, c("year", "month", "day"), sep = "-") %>% 
mutate(
  month = recode(month,
      '01' = "january", '02'= "february", '03'= "march", '04'= "april", '05'= "may",
      '06'= "june", '07'= "july", '08'= "august", '09'= "september", '10'= "october", 
      '11' = "november", '12' = "december")) %>%
  arrange(year, month) %>% 
  select(-day) %>% 
view(fte_snp)
```

    ## Rows: 787 Columns: 2
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): date
    ## dbl (1): close
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

\###Cleaning the Unemployment Data

``` r
fte_unem = read_csv("/Users/mayurialbal/Documents/Data Science/Homework/HW2/HW2/fivethirtyeight_datasets/unemployment.csv") %>% 
  janitor::clean_names() %>% 
pivot_longer(jan:dec, names_to = "month")
```

    ## Rows: 68 Columns: 13
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (13): Year, Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
fte_unem$year <- as.character(fte_unem$year)
view(fte_unem)
```

\###Merge fte_pols and fte_snp, as well as fte_unem

``` r
fte_pols_snp=
  left_join(fte_pols, fte_snp, by= c("year", "month"))
view(fte_pols_snp)
```

``` r
fte_merge=
  left_join(fte_pols_snp, fte_unem, by= c("year", "month"))
view(fte_merge)
```

\####Explanation FTE_POLS: Within the “fte_pols” data set there were 817
observations and 9 variables, after completion of cleaning. The years in
the data set ranged from 1947-2015. The variables found in the data set
included: ‘year’,‘month’,‘gov_gop’,‘gov_dem’,‘sen_gop’, ‘sen_dem’,
‘rep_gop’, ‘rep_dem’ as well as ‘president’. This data set contained
data regarding the amount of national politicians who were either
democratic or republican at any point in the data range.

FTE_SNP: For the data set “fte_snp” there were 787 observations and 3
variables, after cleaning of the data. The years in the data set ranged
from 1950-2015. The variables in the data set were: ‘year’, ‘month’, and
‘close’. This data set contained information regarding stock market
index closing values on the attributed date in this range.

FTE_UNEM The data set “fte_unem” had 816 observations and 3 variables,
after cleaning of data. The years in the data set ranged from 1948-2015.
The variables in the data set were: ‘year, ’month’, and ‘value’. The
‘value’ variable was the reported percentage of unemployment in that
given month within the specified year.

FTE_MERGE This data set was a combination of “fte_pols” and “fte_snp”,
with the later merging of ‘fte_unem. It contained 817 observations and
11 variables. The variables contained in the set were:
’year’,‘month’,‘gov_gop’,‘gov_dem’,‘sen_gop’, ‘sen_dem’, ‘rep_gop’,
‘rep_dem’, ‘president’, ‘close’, and ‘value. The data set ranged from
1947-2015, however the data for variables ’close’ ranged from 1950-2015,
and 1948-2015 for ‘value’. This data set provided a combined set of all
the selected sets to allow for an understanding of governmental
political parties in power and their relation to the stock market as
well as unemployment rates.
